// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using invoice_manger.Models;

namespace invoice_manger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200620210233_last-update")]
    partial class lastupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("invoice_manger.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("Store");

                    b.Property<int>("TotalInvoice");

                    b.Property<int>("TotalNet");

                    b.Property<int>("TotalTaxes");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("invoice_manger.Model.TableRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount");

                    b.Property<int?>("InvoiceId");

                    b.Property<int>("Item");

                    b.Property<int>("Net");

                    b.Property<int>("Price");

                    b.Property<int>("Qty");

                    b.Property<int>("Total");

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("TableRecord");
                });

            modelBuilder.Entity("invoice_manger.Model.TableRecord", b =>
                {
                    b.HasOne("invoice_manger.Model.Invoice")
                        .WithMany("RecordList")
                        .HasForeignKey("InvoiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
